### ISSUE TITLE
Outputs cleanup

### ISSUE THREAD

**Issue by chrisgorgo** [BIDS-Apps/MAGeTbrain#1]
Currently MAGeTbrain BIDS App creates copies of inputs in the output directory (under `input/` subfolder) this is perfectly fine, but could inflate the size of the output package that is archived and needs to be downloaded (in context of integration into a system like OpenNeuro).

One solution would be to remove the intermediate files such as `input/` from the output directory as the last command inside the `group` analysis level.

**Comment by gdevenyi** [comment]
Will add a cleanup to the end of run.py with an option to disable.

**Comment by chrisgorgo** [comment]
Awesome!

**Comment by gdevenyi** [comment]
Fixed.
