### ISSUE TITLE
Incorrect exit codes

### ISSUE THREAD

**Issue by chrisgorgo** [BIDS-Apps/MAGeTbrain#3]
```
mb_register.sh input/atlas/brain4_t1.nii.gz //output/data/input/template/sub-05_ses-anatomy_T1w.nii.gz output/transforms/atlas-template/sub-05_ses-anatomy_T1w.nii.gz	 2DIAGNOSTIC,    25, -7.644600357367e-01, 4.178650846831e-03, 1.3735e+02, 1.1391e-02,
mb_register.sh input/atlas/brain4_t1.nii.gz //output/data/input/template/sub-05_ses-anatomy_T1w.nii.gz output/transforms/atlas-template/sub-05_ses-anatomy_T1w.nii.gz	 2DIAGNOSTIC,    26, -7.647759530172e-01, 1.281254265161e-03, 1.3736e+02, 1.1379e-02,
mb_register.sh input/atlas/brain4_t1.nii.gz //output/data/input/template/sub-05_ses-anatomy_T1w.nii.gz output/transforms/atlas-template/sub-05_ses-anatomy_T1w.nii.gz	 2DIAGNOSTIC,    27, -7.634779090782e-01, 7.040114834627e-04, 1.3737e+02, 1.1281e-02,
mb_register.sh input/atlas/brain4_t1.nii.gz //output/data/input/template/sub-05_ses-anatomy_T1w.nii.gz output/transforms/atlas-template/sub-05_ses-anatomy_T1w.nii.gz	 2DIAGNOSTIC,    28, -7.624503535333e-01, 1.885467981528e-04, 1.3738e+02, 1.1216e-02,
parallel: Error: Output is incomplete. Cannot append to buffer file in /tmp. Is the disk full?
parallel: Error: Change $TMPDIR with --tmpdir or use --compress.
Warning: unable to close filehandle properly: Cannot allocate memory during global destruction.
2018-03-08 22:10:57 UTC [     info] Cleaning up. Done
```
yield 0 exit code

See https://openneuro.org/datasets/ds001246/versions/00001?app=MAGeTbrain&version=11&job=5aa1932e8bd3890001005afb for more details

**Comment by gdevenyi** [comment]
Yup, I'm definitely not handling error codes in the python wrapper. My bad, will fix up.

Sidenote: ANTs tools don't uniformly return proper exit codes, so sometimes this will be unavoidable.

**Comment by gdevenyi** [comment]
Pushed some updates to qbatch to fix this. Will tag as soon as Circle completes.

**Comment by chrisgorgo** [comment]
Awesome! Thanks!

**Comment by gdevenyi** [comment]
Hey @chrisfilo I updated bids-validator and it fails on the example datasets now, should I revert or are there new sets?

**Comment by chrisgorgo** [comment]
That's not good. What's the error? Where are the examples from? Could you share a circleci link?

**Comment by gdevenyi** [comment]
https://circleci.com/gh/BIDS-Apps/MAGeTbrain/64

It's probably due to me using a custom low-res dataset you made for me...

**Comment by gdevenyi** [comment]
https://github.com/BIDS-Apps/MAGeTbrain/blob/master/circle.yml#L15

**Comment by chrisgorgo** [comment]
https://osf.io/8s29u/download

You will have to update the circle yml file with a download command similar to this syntax https://github.com/BIDS-Apps/freesurfer/blob/master/circle.yml#L19

**Comment by gdevenyi** [comment]
Fixed and release stamped. https://github.com/BIDS-Apps/MAGeTbrain/releases/tag/v0.2.2.2
